### ISSUE TITLE
documentation on how to alter example?

### ISSUE THREAD

**Issue by BretG137** [ONLYOFFICE/Docker-DocumentServer#396]
I have set up the community edition document server using the docker compose file.  Following the instructions, I set up the example file and everything works well but how do I alter the example?  How to change the usernames or base url?  I can't find any documentation on this.  Thanks!

**Comment by ShockwaveNN** [comment]
Hi, If you used integrated into our default docker image example - it cannot be modified since it's distributed as static binary (to remove dependency of nodejs)

But if you want to setup it manually - code of example located [here](https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/nodejs)
There is some documentation and code rather straight forward (if you want change usernames for example)

**Comment by BretG137** [comment]
I don't understand:

1. I went to your link but it says:
"If you want to experiment with the editor configuration, modify the parameters in the \views\editor.ejs file."
when you click on parameters it shows the files you would want to edit, i.e. "John Smith" etc. but when you view the contents of \view\editor.ejs in the github directory it contains entirely different code.

2. Supposing that I was able to edit the user names etc in this file then what?  I assume I would replace example in:
sudo docker exec $(sudo docker ps -q) sudo supervisorctl start ds:example
but where would this example file/directory need to be?  inside the www directory of the docker container?  What should the contents of the example directory file be?

3. I noticed i cannot change the name of the files that it onlyoffice creates. They are all just called 'new' without anyway of changing it.  Uploading a file retains the name.  Is there a way to change the name of document?

4. Where are the documents stored?  /var/www/onlyoffice/documentserver-example/public/files doesn't seem to have any files in it.  I can see that there are some documents in the cache, /var/lib/onlyoffice/documentserver/App_Data/cache/files.  

5.  How is this intended to be used?  Seems unusable in it's default configuration.  Is it only intended as a an example for administrators to use in larger deployments?  i.e. not intended for people like me who tinker with in a homelab?  

Thanks!

**Comment by ShockwaveNN** [comment]
> but when you view the contents of \view\editor.ejs in the github directory it contains entirely different code.

I think it's a typo and those options are at [vievs/config.ejs](https://github.com/ONLYOFFICE/document-server-integration/blob/master/web/documentserver-example/nodejs/views/config.ejs)

> I assume I would replace example in:
sudo docker exec $(sudo docker ps -q) sudo supervisorctl start ds:example
but where would this example file/directory need to be?

No, DocumentServer docker image (and installations) by default comes with test example which do not allow any customization. It comes as complied binary to remove dependency of `nodejs`
You can setup manually example on any server which can access to DocumentServer and run it

> Is there a way to change the name of document?

Not via test example

> Where are the documents stored?

`/var/lib/onlyoffice/documentserver-example/files/`

> Is it only intended as a an example for administrators to use in larger deployments?

It's purpose show administrators and developers how to integrate DocumentServer into their own DMS (Document Managmenet Systems).
It shouldn't be used in any production environment (even home one), only for debugging purposes (that's why it stopped by default)
If you need to use DocumentServer - better to connect it to other DMS, like ONLYOFFICE CoummunityServer, Nextcloud, Owncloud and etc

**Comment by BretG137** [comment]
I see.  I decided to use the workspace ce and it works well.  Thank you!
