### ISSUE TITLE
Docker image ARM

### ISSUE THREAD

**Issue by talesam** [ONLYOFFICE/Docker-DocumentServer#405]
Is there no binary for ARM64?

**Comment by ShockwaveNN** [comment]
We currently have no fully working version of ARM64, ready for production but we've made some improvement since

https://github.com/ONLYOFFICE/DocumentServer/issues/152

I really hope that in future several release we'll able to release this version

But currently I'm closing it until we close https://github.com/ONLYOFFICE/DocumentServer/issues/152
