### ISSUE TITLE
healthcheck returns false on new docker setup

### ISSUE THREAD

**Issue by cromulus** [ONLYOFFICE/Docker-DocumentServer#59]
Steps to reproduce:
```
sudo docker pull onlyoffice/documentserver
sudo docker run -i -t -d -p 80:80 \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
    -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice onlyoffice/documentserver
wget http://localhost/healthcheck
```

Any ideas?

**Comment by ShockwaveNN** [comment]
Try to not mount `/app/onlyoffice/DocumentServer/lib`
I think there is `Error: EACCES: permission denied, mkdir '/var/lib/onlyoffice/documentserver'` error in logs, because `/app/onlyoffice/DocumentServer/lib` folder have no permissions to user `onlyoffice` to write into

**Comment by Taste-IT** [comment]
Hi,
i have the same problem. I have mounted the ../lib Dir and permissions for root correct. i have no user with name onlyoffice. What i do not understand is, where should the directory created? On localhost or in Docker?

**Comment by ShockwaveNN** [comment]
@Taste-IT Hi.
Directory `/app/onlyoffice/DocumentServer/lib` should be present on host machine, not inside docker.

**Comment by Taste-IT** [comment]
Hi ShockwaveNN,
yes /lib, /data and /logs exists. I got this problem since latest update of OO, before it works well. I delted the docker image and redownloaded newest OO, copied Certs into correct Dir and cant now start Document Server "Something went wrong..." is the message on Document Server Side. Any Idea?

**Comment by ShockwaveNN** [comment]
@Taste-IT I think something interisting should be in logs - see inside `/var/log/onlyoffice` in docker, or in host `/app/onlyoffice/DocumentServer/logs` if you mounted volume if like said earlier

**Comment by Taste-IT** [comment]
Hi,
in nginx log - "..[crit] 411#0: *57 connect() to [::1]:8000 failed (99: Cannot assign requested address) while connecting to upstream, client .."
in out.log "..Error: EACCES: permission denied, mkdir '/var/lib/onlyoffice/documentserver' .."

**Comment by Taste-IT** [comment]
I use OO Installation guide for docker and Document Server installation. Is there missing some fact i have todo before, perhaps?

**Comment by ShockwaveNN** [comment]
It same error as from topic starter.
If you don't need use separate PostreSQL server - you can remove `-v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice` and I hope everything will be fine

**Comment by Taste-IT** [comment]
Yes it is. I cant use a seperate PostgreSQL Server. A way up you said User OnlyOffice has no permission. On Host i have no user like this. Perhaps thats the problem. How to solve this. I wonder that no other have this problem, since i use the office Howto and my System is Debian stable with OO in Subdomain and Port Forward from 443 -> 8888. ?!

**Comment by ShockwaveNN** [comment]
No, no, you need mount `lib` IF you use separate Postgre, in your case you can remove this volume.
Also you can change permission to /var/lib/onlyoffice to something like 777, but it's not secure

**Comment by Taste-IT** [comment]
Forgett to write - i dont have this directory

**Comment by ShockwaveNN** [comment]
Or, sorry, I meant `/app/onlyoffice/DocumentServer/lib` on host

**Comment by Taste-IT** [comment]
Hi,
i did and Document Server starts, but the Security is a problem. How to correct this finaly? It seems that the User in Dockerimage must have rights on this local directory, right? So how to solve this? Another major problem still exists and thats since the beginning of the integration in NextCloud -> Changes in an existing document didnt write back to the cloud.
in out.log i see "...Error: Error response: statusCode:400 ;body:
{"error":1} ... "
Thanks for your help.

**Comment by Taste-IT** [comment]
Oh new documents will also not write back to nc, too.

**Comment by Taste-IT** [comment]
Backup to permissions - this happend not before actual version of OO, seems they changed something...

**Comment by ShockwaveNN** [comment]
> but the Security is a problem. How to correct this finaly
We long aware of this, and understand that is a problem, but currently have no perfect solution. We working on it.

> NextCloud -> Changes in an existing document didnt write back to the cloud.
Please ask all question about NextCloud in https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues

**Comment by Taste-IT** [comment]
Ok, i will do and wait for an update... Thanks so far.

**Comment by igwyd** [comment]
Hello @cromulus and @Taste-IT, sorry for the late reply, the error is not repiting.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
