### ISSUE TITLE
Limiting access to docker container to/from internet

### ISSUE THREAD

**Issue by ostasevych** [ONLYOFFICE/Docker-DocumentServer#641]
Hi! I use OnlyOffice in a docker container as a service for Nextcloud. I would like to restrict access to the OnlyOffice docker container from and to Internet. Please, give your advice, how to arrange that without making troubles to its functioning (with the means of docker itself/iptables whatever). Thank you.

**Comment by igwyd** [comment]
Hello @ostasevych, with docker i see only using internal network option ```--internal=true```, but there may be problems with opening documents. Using proxy servers and a firewall I think would be the right thing to do in local network. Unfortunately, we do not have guides on how to set up a network, because this is the task of network administrators, network settings depend on the specific requirements of users and can be very different. Our containers don't need constant internet access to work, so you can isolate as you wish.

**Comment by Rita-Bubnova** [comment]
We close this issue. Feel free to comment or reopen it if you got further questions.
