### ISSUE TITLE
Multi users can not use group rows and columns in xlsx at the same time.

### ISSUE THREAD

**Issue by zgpnuaa** [ONLYOFFICE/Docker-DocumentServer#701]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When multiple people are editing an Excel sheet using the group data feature, clicking the plus and minus signs on the left does not expand or collapse the groups, but the cell content can be edited and modified.
However, when used by a single person, the plus and minus signs can be clicked to expand and collapse."
![image](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/38033949/dbfe8bbb-34af-4f0c-8d13-85e2f2dc1dba)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Multiple people using the group data feature in an XLSX file, clicking the plus and minus signs on the left.

**What is the expected behavior?**

I hope that when multiple people are working with group data in xlsx, they can also expand and collapse the groups at the same time.

**Did this work in previous versions of DocumentServer?**
no

**DocumentServer Docker tag:**
7.5.1
**Host Operating System:**
Ubuntu 18.04

**Comment by VladimirProkofiev52** [comment]
Hello! @zgpnuaa 

I couldn't reproduce your issue.
Could you please confirm if the problem occurs only with a specific file or with all files?
If the problem is related to a specific file, please send it to me.

Currently, we've released version 8.0.1 of the editor. Try updating the editor to the latest version and see if the issue persists.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
