### ISSUE TITLE
Can't add fonts correctly

### ISSUE THREAD

**Issue by Lakhtion** [ONLYOFFICE/Docker-DocumentServer#746]
I have documentsserver in conjunction with nextcloud.
I mounted it in compose:
- /media/onlyoffice_documentserver/fonts:/usr/share/fonts

By default, for some reason, I do not have the most standard fonts, for example calibri, arial, times new roman. Is this like this for everyone? I need fonts with Cyrillic support.
What’s surprising is that even if I don’t have the choice of the font I need in the documentserver, it is displayed when I open the document (if it was already there in any text) and I can print on it. Moreover, I can select a font that is not in the list by entering it manually. I get a warning, but everything works.
Next I follow the instructions https://helpcenter.onlyoffice.com/ru/installation/docs-community-install-fonts-linux.aspx
On the host, I upload calibri fonts (pulled out of Windows) in the amount of 6 files into /media/onlyoffice_documentserver/fonts, execute documentsserver-generate-allfonts.sh inside the container - no errors occur, everything is ok.
When I open a document, I see crooked characters on any layout. The font itself appears, but when you try to select a font, some other one is selected, and the characters are displayed crookedly in any language. Firefox browser, clearing cache does not help. Newly installed Chrome on Windows also has crooked symbols.
At the same time, everything is displayed correctly through the Yandex browser. Through Firefox on Ubuntu, everything is also displayed correctly. Through the Onlyoffice application on Android, everything is also displayed as it should. And through the nextcloud application and through the Firefox browser on Android, I again see crooked characters. I tried deleting the cache of firefox, nextcloud, android web view - it did not help. It seems that the problem is still in the onlyoffice instance.
Please help. I saw similar topics, but a simple cache clearing helped everywhere. No to me.
Documentserver version 8.0.1.31, host - debian 11 (openmediavault), docker 26.1.4

**Comment by igwyd** [comment]
Hello @Lakhtion, yes the docker distribution have only our core fonts by default. 

> What’s surprising is that even if I don’t have the choice of the font I need in the documentserver, it is displayed when I open the document (if it was already there in any text) and I can print on it. Moreover, I can select a font that is not in the list by entering it manually. I get a warning, but everything works.

When you select a font that does not exist on the server, a warning appears that one of the system fonts will be used if it matches or will be select automatically from the most similar ones.

I checked you case with chrome and firefox on windows and linux, adding fonts works correctly. Most likely, the problem is not in the server, but in the cache in your devices, browsers, cache proxy(do you use clouflare maybe?), VPN or someting else. For a clean test, install your browsers on a new clean virtual machine and test your fonts.

**Comment by Lakhtion** [comment]
> I checked you case with chrome and firefox on windows and linux, adding fonts works correctly. Most likely, the problem is not in the server, but in the cache in your devices, browsers, cache proxy(do you use clouflare maybe?), VPN or someting else. For a clean test, install your browsers on a new clean virtual machine and test your fonts.

Greetings. I already wrote that I tried to delete all kinds of caches. I tried to install pure Chrome - the problem is there too. Today I tried to install a clean Windows 10 via vmware and immediately open the document in Edge - there is a problem there too. All the characters are crooked, the fonts in the list are mixed, it’s impossible to work.
I tried resetting the cache both with ctrl+f5 and through the browser settings, but I think it doesn’t matter, since the problem is reproduced on a completely clean operating system and browser.

**Comment by igwyd** [comment]
Then maybe the problem is in some fonts, could you attach the fonts with which you are experiencing problems?

**Comment by Lakhtion** [comment]
> Then maybe the problem is in some fonts, could you attach the fonts with which you are experiencing problems?
Yes, you can try with it. I pulled it from Windows 11, this is system fonts, and it works correctly in MS Office.
Based on the test results, I realized that apparently the calibri is working correctly, but not arial and times. I tried to install them separately.
I also could not figure out how to 100% reset the browser cache in a situation with Firefox - sometimes even completely deleting all history, cookies, cache and generally everything possible for the entire time does not help. And ctrl+f5 for a snack. And sometimes it works. With chrome and Yandex browser it seems to be simpler. I test changes in Yandex now, because I guaranteed can see any results there.
[fonts.zip](https://github.com/user-attachments/files/15945137/fonts.zip)

**Comment by igwyd** [comment]
Firefox has a guide in support on how to clear the cache - [here](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache#:~:text=the%20Firefox%20cache%3A-,Click%20the%20menu%20button,click%20the%20Clear%20Now%7D%20button.).
It doesn't matter whether the fonts are in the ```/usr/share/fonts``` or into a nested folders.
I checked your fonts and they are correctly added and displayed, so the problem is in your stand. You need to localize the issue. Try installing onlyoffice-documentserver and nextcloud on a clean machine without a proxy and test adding fonts. If everything works, then add your settings one by one to get closer to the problematic stand and I think you will be able to find the error.

**Comment by Lakhtion** [comment]
> and I think you will be able to find the error

Thanks, I figured out the issue!
The error was that I had the item cache assets enabled in Nginx proxy manager. 
The proxy manager cached onlyoffice data in its container in addition to my browsers. I disabled cache assets and now, when adding fonts and resetting the cache in the browser for my domain, everything is ok. 
PS by the way, ctrl+f5 does not help, need to reset cache manually, but all works now.

I think we can close this thread, thanks
