### ISSUE TITLE
Missing fonts like Calibri

### ISSUE THREAD

**Issue by gazm2k5** [ONLYOFFICE/Docker-DocumentServer#775]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.3.4

### Expected Behavior

I am running ONLYOFFICE documentserver in a container for use in NextCloud.

I created a volume for fonts:
- /docker-volumes/onlyoffice/fonts:/usr/share/fonts/truetype/custom
and put calibri.ttf in there. But the font hasn't appeared in ONLYOFFICE.

I am very confused about the documentation for ONLYOFFICE as it says fonts like calibri are included but they aren't.
https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx

It also says I can run:
> /usr/bin/documentserver-generate-allfonts.sh
to add the fonts I've added to the custom fonts folder, but no such file exists.

### Actual Behavior

Font is missing from ONLYOFFICE.

**Comment by igwyd** [comment]
Hello @gazm2k5, sorry for the last reply.
> I am very confused about the documentation for ONLYOFFICE as it says fonts like calibri are included but they aren't.

It says there that: "When installed it will **check** the presence of the following font files **in the system**", but it doesn't say that they are included in the distribution. But I agree that this could be misleading. I will ask the technical writers to change the wording.

By the way, were you able to add the calibri font?

**Comment by gazm2k5** [comment]
No, I couldn't figure out how to get the fonts that I added to the custom fonts folder to appear.

**Comment by igwyd** [comment]
I see you are using documentserver 8.1.3 version. Did you follow all the steps in the guide https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx including clearing your browser cache?
1. Install the font by copying it to /usr/share/fonts/ (to the computer with ONLYOFFICE Docs installed). Or as you did, mounted the folder.
2. Open the /usr/bin folder.
3. Run the documentserver-generate-allfonts.sh file inside docker container. (or just restart docker container, because generating fonts starts every start container)
4. Clear the browser cache and reopen the page.

PS Starting with version 8.2.0, there is no need to clear your browser cache.

**Comment by gazm2k5** [comment]
It does seem to have added now. I think the container restart must have loaded the new fonts.
