### ISSUE TITLE
Information about how to restart safely

### ISSUE THREAD

**Issue by y0va** [ONLYOFFICE/Docker-DocumentServer#97]
There should be some notes about how to restart / update the docker container safely, so that all loaded documents are saved. I lost some data because of assuming that it goes fine by normal restart procedure.

**Comment by aaronouthier** [comment]
An obscure article I came across recently, mentions how to do a safe shutdown by forcefully disconnecting all users.

Article can be found here: [https://helpcenter.onlyoffice.com/server/linux/document/troubleshooting.aspx](url)

**Comment by aaronouthier** [comment]
If using Docker, you'll need to execute that from inside the docker container.

I believe this code fragment should work, but I have not tested to verify:
`docker exec -it {name or id of document server container} /bin/sh documentserver-prepare4shutdown.sh`

Obviously, substitute the actual docker container name or id for your system into the appropriate place above.

**Comment by aaronouthier** [comment]
Oops, slight correction. I found the same article under the Docker section, instead of the Linux Section.

`sudo docker exec <CONTAINER> documentserver-prepare4shutdown.sh`

Found THAT article at the bottom of this page:
[https://helpcenter.onlyoffice.com/server/docker/document/troubleshooting.aspx](url)

**Comment by drebs** [comment]
The link above is correct but doesn't match the actual URL that opens when you click it. This is the correct place for that documentation: https://helpcenter.onlyoffice.com/server/docker/document/troubleshooting.aspx

I copy the relevant content below in case the link ever gets outdated:

## Document Server usage issues

**Q:** Data loss has occured when stopping Document Server. How to prevent data loss?

**A:** Due to the operational characteristic, Document Server saves a document only after the document has been closed by all the users who edited it. To avoid data loss, you must forcefully disconnect the Document Server users when you need to stop Document Server in cases of the application update, server reboot etc. To do that, execute the following script on the server where Document Server is installed:

```
sudo docker exec <CONTAINER> documentserver-prepare4shutdown.sh
```

* Executing the script may take a long time (up to 5 minutes).
* Disconnecting users may take a long time (up to 5 minutes).

**Comment by ShockwaveNN** [comment]
I think I'll close this issue since this is more a question (and it's resolved) than an issue
